# Infos
name: TheGoldEconomy
version: '1.6.6'
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex
api-version: 1.18

# Data
main: confusedalex.thegoldeconomy.TheGoldEconomy
softdepend: [ PlaceholderAPI ]
loadbefore: [ Towny ]
depend: [ Vault ]