# Infos
name: TheGoldEconomy
version: '1.5.1'
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex
fork-author: Kiana
api-version: 1.18

# Data
load: STARTUP
main: confusedalex.thegoldeconomy.TheGoldEconomy
loadbefore: [Towny]
depend: [Vault]