# Infos
name: TheGoldEconomy
version: "1.8.1"
description: A simple gold based Economy plugin that just works.
author: ConfusedAlex
api-version: 1.18

# Data
main: dev.confusedalex.thegoldeconomy.TheGoldEconomy
softdepend: [PlaceholderAPI]
loadbefore: [Towny]
depend: [Vault]

permissions:
  thegoldeconomy.balance:
    default: true
  thegoldeconomy.deposit:
    default: true
  thegoldeconomy.withdraw:
    default: true
  thegoldeconomy.pay:
    default: true
  thegoldeconomy.balance.others:
    default: true
